"""
Calculates the following metrics per notebook log (one row per notebook):
- total_duration: seconds between first and last event
- total_working_duration: total duration minus inactive gaps > 30 minutes (1800s)
- total_clipboard_events: count of copy+cut+paste
- clipboard_lengths: JSON list of lengths (integers) for clipboard events in timestamp order
- execution_events_count: number of execute events
- execution_status_success: count of execute events with status success
- execution_status_error: count of execute events with status error
- added_characters: characters added across saved diffs
- removed_characters: characters removed across saved diffs
- net_character_change: added characters minus removed characters
- added_lines: number of added diff lines
- removed_lines: number of removed diff lines
Additionally, for each distinct cell seen in the logs, the script creates column groups
using a readable label (for example, ``cell_1``):
  cell_1_total_duration
  cell_1_working_duration
  cell_1_clipboard_events
  cell_1_clipboard_lengths  (JSON list)
  cell_1_exec_count
  cell_1_exec_success
  cell_1_exec_error

Output: a single CSV file (student_analytics.csv) where each row is a notebook
(student), plus ``cell_mapping.csv`` which maps readable labels to stable Jupyter
cell IDs, and ``cell_execution_summary.csv`` with one readable row per cell.

This file is admittedly generated by GPT 5 and lacks thorough testing due to time constraints!
"""

import os
import glob
import re
import json
import numpy as np
import pandas as pd
from datetime import datetime

# CONFIGURATION
LOG_GLOB = "*.ipynb.log"
OUTPUT_FILENAME = "student_analytics.csv"
MAPPING_FILENAME = "cell_mapping.csv"
EXECUTION_SUMMARY_FILENAME = "cell_execution_summary.csv"
IDLE_THRESHOLD = 30 * 60.0  # 30 minutes in seconds
LEGACY_EXECUTION_MATCH_WINDOW = 5.0  # seconds

# HELPERS
def parse_timestamp(ts_str):
    # Accept a couple of ISO-like formats commonly used
    for fmt in ("%Y-%m-%dT%H:%M:%S.%fZ", "%Y-%m-%dT%H:%M:%SZ"):
        try:
            return datetime.strptime(ts_str, fmt)
        except Exception:
            continue
    # fallback: try fromisoformat after removing trailing Z
    try:
        if ts_str.endswith("Z"):
            return datetime.fromisoformat(ts_str[:-1])
        return datetime.fromisoformat(ts_str)
    except Exception:
        raise ValueError(f"Unrecognized timestamp format: {ts_str}")

def sanitize_cell_id(cell_id: str) -> str:
    # Turn arbitrary cell id into safe header fragment (alphanumeric + underscores)
    if cell_id is None:
        return "unknown"
    s = re.sub(r"[^0-9A-Za-z]+", "_", str(cell_id))
    # avoid empty
    return s if s else "cell"

def extract_student_name(filepath: str) -> str:
    return os.path.basename(filepath).split(".")[0]

def parse_log_file(path: str):
    """
    Parse log lines into a list of events dictionaries with keys:
      ts (datetime), event (string), cell (string or None), cell_label (string or None),
      length (int or np.nan), status (str or None), raw (str)
    """
    events = []
    with open(path, "r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            # timestamp at start in [..]
            m = re.match(r"^\[([^\]]+)\]", line)
            if not m:
                continue
            ts_field = m.group(1)
            try:
                ts = parse_timestamp(ts_field)
            except Exception:
                continue

            # event type
            ev_m = re.search(r"\[(focusin|focusout|copy|cut|paste|execute|initial save|save(?: \d+)?)\]", line)
            if not ev_m:
                # not an event we care about
                continue
            ev = ev_m.group(1)

            # New logs use the consistent positional "cell N" format. Older
            # logs may still use "code cell N", "markdown cell N", or a UUID.
            cell = None
            cell_label = None
            m_cell = re.search(r"\[cell ID:\s*([0-9A-Za-z\-\_:]+)\]", line)
            if m_cell:
                cell = m_cell.group(1)
            else:
                m_alt = re.search(r"\[(?:(code|markdown)\s+)?cell\s*(\d+)\]", line)
                if m_alt:
                    # Keep old positional identifiers separate from UUIDs. This
                    # avoids incorrectly merging them in historical mixed logs.
                    cell_type = m_alt.group(1) or "positional"
                    cell = f"legacy_{cell_type}_cell_{m_alt.group(2)}"
                    cell_label = f"cell_{m_alt.group(2)}"
                else:
                    m_alt2 = re.search(r"\[cell:\s*([0-9A-Za-z\-\_:]+)\]", line)
                    if m_alt2:
                        cell = m_alt2.group(1)

            m_label = re.search(r"\[cell label:\s*([^\]]+)\]", line)
            if m_label:
                cell_label = m_label.group(1).strip()

            len_m = re.search(r"length:\s*(\d+)", line)
            length = int(len_m.group(1)) if len_m else np.nan

            status = None
            if ev.startswith("execute") or ev == "execute":
                stat_m = re.search(r"status:\s*(success|error)", line)
                if stat_m:
                    status = stat_m.group(1)

            events.append({"ts": ts, "event": ev, "cell": cell, "cell_label": cell_label,
                           "length": length, "status": status, "raw": line})

    if not events:
        return pd.DataFrame([], columns=["ts", "event", "cell", "cell_label", "length", "status", "raw"])
    df = pd.DataFrame(events).sort_values("ts").reset_index(drop=True)
    return df


def associate_legacy_execution_events(df: pd.DataFrame) -> pd.DataFrame:
    """Attach UUID-only execution events in old logs to a nearby numbered cell.

    Earlier extension versions logged focus and save events as ``[code cell N]``
    but executions as a UUID. An execution is normally surrounded by events for
    the active cell, so we use the nearest numbered event within five seconds.
    Events outside that window remain unlabelled rather than being guessed.
    """
    if df.empty:
        return df

    numbered = df[
        df["cell"].fillna("").str.startswith("legacy_") & df["cell_label"].notna()
    ]
    legacy_exec_indexes = df.index[
        (df["event"] == "execute")
        & df["cell_label"].isna()
        & ~df["cell"].fillna("").str.startswith("legacy_")
    ]

    for index in legacy_exec_indexes:
        if numbered.empty:
            continue
        differences = (numbered["ts"] - df.at[index, "ts"]).abs()
        nearest_index = differences.idxmin()
        if differences.loc[nearest_index].total_seconds() <= LEGACY_EXECUTION_MATCH_WINDOW:
            df.at[index, "cell"] = numbered.at[nearest_index, "cell"]
            df.at[index, "cell_label"] = numbered.at[nearest_index, "cell_label"]
    return df

# METRIC COMPUTATIONS
def compute_total_duration(df: pd.DataFrame) -> float:
    if df.empty:
        return 0.0
    return (df.ts.iloc[-1] - df.ts.iloc[0]).total_seconds()

def compute_working_duration(df: pd.DataFrame, idle_threshold: float = IDLE_THRESHOLD) -> float:
    """
    Working duration = total span between first and last event minus any gaps > idle_threshold.
    """
    if df.empty:
        return 0.0
    times = df.ts.tolist()
    total_span = (times[-1] - times[0]).total_seconds()
    idle = 0.0
    for t1, t2 in zip(times, times[1:]):
        gap = (t2 - t1).total_seconds()
        if gap > idle_threshold:
            idle += gap
    working = max(0.0, total_span - idle)
    return working

def compute_clipboard_events(df: pd.DataFrame):
    cb_df = df[df.event.isin(["copy","cut","paste"])]
    total_cb = cb_df.shape[0]
    lengths = cb_df.length.dropna().astype(int).tolist()
    return total_cb, lengths

def compute_execution_stats(df: pd.DataFrame):
    exec_df = df[df.event.str.contains("execute")]
    total_exec = exec_df.shape[0]
    success = exec_df[exec_df.status == "success"].shape[0]
    error = exec_df[exec_df.status == "error"].shape[0]
    return total_exec, success, error


def compute_change_stats(path: str):
    """Count the volume of saved additions and removals in a change log.

    Diff body lines begin with ``+ `` or ``- ``. The prefix is excluded from the
    character count; all remaining logged characters are counted exactly as they
    appear in the diff (including JSON punctuation when present).
    """
    added_characters = removed_characters = 0
    added_lines = removed_lines = 0

    with open(path, "r", encoding="utf-8") as fh:
        for line in fh:
            if line.startswith("+ "):
                added_lines += 1
                added_characters += len(line[2:].rstrip("\n"))
            elif line.startswith("- "):
                removed_lines += 1
                removed_characters += len(line[2:].rstrip("\n"))

    return {
        "added_characters": added_characters,
        "removed_characters": removed_characters,
        "net_character_change": added_characters - removed_characters,
        "added_lines": added_lines,
        "removed_lines": removed_lines,
    }

def compute_per_cell_metrics(df: pd.DataFrame):
    """
    For each non-null cell, compute the same group of metrics but restricted to that cell's events.
    Returns a dict mapping sanitized_cell_id -> metrics dict.
    """
    result = {}
    # consider only non-null cell ids
    cells = [c for c in df.cell.unique() if pd.notna(c)]
    for cell in cells:
        grp = df[df.cell == cell].sort_values("ts")
        if grp.empty:
            continue
        total_duration = compute_total_duration(grp)
        working_duration = compute_working_duration(grp)
        total_cb, lengths = compute_clipboard_events(grp)
        exec_count, exec_success, exec_error = compute_execution_stats(grp)
        san = sanitize_cell_id(cell)
        result[san] = {
            "cell_raw": cell,
            "total_duration": total_duration,
            "working_duration": working_duration,
            "clipboard_events": total_cb,
            "clipboard_lengths": lengths,
            "exec_count": exec_count,
            "exec_success": exec_success,
            "exec_error": exec_error
        }
    return result


def resolve_cell_labels(df: pd.DataFrame) -> dict:
    """Map each log cell reference to a readable, unique column prefix.

    New logs provide ``[cell N]``. Historical UUID-only execution entries are
    first matched to a nearby numbered event when the evidence is strong enough.
    """
    labels = {}
    used = set()
    for cell in [c for c in df.cell.unique() if pd.notna(c)]:
        cell_labels = df.loc[df.cell == cell, "cell_label"].dropna().unique()
        if len(cell_labels):
            label = sanitize_cell_id(cell_labels[0])
            labels[cell] = label
            used.add(label)

    fallback_number = 1
    for cell in [c for c in df.cell.unique() if pd.notna(c) and c not in labels]:
        while f"unlabelled_cell_{fallback_number}" in used:
            fallback_number += 1
        label = f"unlabelled_cell_{fallback_number}"
        labels[cell] = label
        used.add(label)
        fallback_number += 1
    return labels

# MAIN: iterate over logs and build a single wide dataframe
def process_folder(folder: str):
    rows = []
    mapping_rows = []
    execution_rows = []
    # Collect union of cell IDs across all students to ensure consistent columns
    all_cell_keys = set()

    filepaths = glob.glob(os.path.join(folder, LOG_GLOB))
    if not filepaths:
        print(f"No log files found in {folder} matching {LOG_GLOB}")
        return

    for path in sorted(filepaths):
        student = extract_student_name(path)
        df = parse_log_file(path)
        df = associate_legacy_execution_events(df)
        row = {"student": student}
        cell_labels = resolve_cell_labels(df)

        for raw_cell, label in cell_labels.items():
            mapping_rows.append({
                "student": student,
                "cell_label": label,
                "cell_id": raw_cell if not raw_cell.startswith("legacy_") else "",
                "log_cell_reference": raw_cell,
            })

        # Overall metrics
        row["total_duration"] = compute_total_duration(df)
        row["total_working_duration"] = compute_working_duration(df)
        total_cb, cb_lengths = compute_clipboard_events(df)
        row["total_clipboard_events"] = total_cb
        # store clipboard lengths as JSON string to keep as single CSV cell
        row["clipboard_lengths"] = json.dumps(cb_lengths)
        exec_total, exec_success, exec_error = compute_execution_stats(df)
        row["execution_events_count"] = exec_total
        row["execution_status_success"] = exec_success
        row["execution_status_error"] = exec_error
        row.update(compute_change_stats(path))

        # Per-cell
        cell_metrics = compute_per_cell_metrics(df)
        for san_id, metrics in cell_metrics.items():
            label = cell_labels[metrics["cell_raw"]]
            all_cell_keys.add(label)
            # create flattened columns with clear names
            row[f"{label}_total_duration"] = metrics["total_duration"]
            row[f"{label}_working_duration"] = metrics["working_duration"]
            row[f"{label}_clipboard_events"] = metrics["clipboard_events"]
            row[f"{label}_clipboard_lengths"] = json.dumps(metrics["clipboard_lengths"])
            row[f"{label}_exec_count"] = metrics["exec_count"]
            row[f"{label}_exec_success"] = metrics["exec_success"]
            row[f"{label}_exec_error"] = metrics["exec_error"]
            if metrics["exec_count"]:
                execution_rows.append({
                    "student": student,
                    "cell": label,
                    "execution_count": metrics["exec_count"],
                    "success_count": metrics["exec_success"],
                    "error_count": metrics["exec_error"],
                })

        rows.append(row)

    # Build DataFrame and ensure all cell columns appear (fill missing with 0 or empty list)
    df_out = pd.DataFrame(rows).set_index("student")

    # Ensure consistent columns for all cells found across dataset
    for san in sorted(all_cell_keys):
        cols = [
            f"{san}_total_duration",
            f"{san}_working_duration",
            f"{san}_clipboard_events",
            f"{san}_clipboard_lengths",
            f"{san}_exec_count",
            f"{san}_exec_success",
            f"{san}_exec_error",
        ]
        for c in cols:
            if c not in df_out.columns:
                # Fill with sensible defaults
                if c.endswith("_clipboard_lengths"):
                    df_out[c] = json.dumps([])
                elif c.endswith("_clipboard_events") or c.endswith("_exec_count") or c.endswith("_exec_success") or c.endswith("_exec_error"):
                    df_out[c] = 0
                else:
                    df_out[c] = 0.0

    # Reorder columns: overall metrics first, then cells in lexicographic order
    overall_cols = [
        "total_duration",
        "total_working_duration",
        "total_clipboard_events",
        "clipboard_lengths",
        "execution_events_count",
        "execution_status_success",
        "execution_status_error",
        "added_characters",
        "removed_characters",
        "net_character_change",
        "added_lines",
        "removed_lines",
    ]
    cell_cols = [c for c in df_out.columns if c not in overall_cols]
    df_out = df_out[overall_cols + sorted(cell_cols)]

    outpath = os.path.join(folder, OUTPUT_FILENAME)
    df_out.to_csv(outpath, index=True)
    print(f"Saved analytics to {outpath}")

    mapping_path = os.path.join(folder, MAPPING_FILENAME)
    pd.DataFrame(mapping_rows).to_csv(mapping_path, index=False)
    print(f"Saved cell mapping to {mapping_path}")

    execution_path = os.path.join(folder, EXECUTION_SUMMARY_FILENAME)
    pd.DataFrame(
        execution_rows,
        columns=["student", "cell", "execution_count", "success_count", "error_count"],
    ).to_csv(execution_path, index=False)
    print(f"Saved execution summary to {execution_path}")

if __name__ == "__main__":
    import sys
    if len(sys.argv) != 2:
        print("Usage: python compute_analytics.py /path/to/log/folder")
        sys.exit(1)
    folder = sys.argv[1]
    process_folder(folder)
